#!/bin/bash

RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
GRAY='\033[0;37m'
NC='\033[0m' # No Color


if [ "$1" = "-h" ] || [ "$1" = "--h" ] || [ "$1" = "--help" ] || [ "$1" = "help" ]; then
  printf "${BLUE}Usage:${NC} docker-start ${GRAY}service${NC}\n"
  echo "Launch docker-compose build with variable substitution"
  printf "\t${GRAY}service${NC} - The service name to build from docker-compose file. Default - all\n"

  exit
fi

service_name=$1

if [ "$service_name" != "wss-go" ] && [ "$service_name" != "wss-redis" ] && [ "$service_name" != "wss-nginx" ] && [ "$service_name" != "" ]; then
  printf "${RED}Error: service '$service_name' not allowed.${NC}"
fi

export HOST_UID="$(id -u)"
export HOST_GID="$(id -g)"
docker-compose build $service_name
docker-compose up -d

